### ISSUE TITLE
Host.docker.internal not resolved on Linux

### ISSUE THREAD

**Issue by amitbend** [botfront/botfront-starter#1]
Hi!
I'm tried running `docker-compose up`, but after building the image successfully I'm getting this error which makes the container to exit
`Error: unable to connect to database: mongodb://host.docker.internal:27017/bf` 

I can see many more errors right after that, if needed I'll copy them here (it's quite a long log)

**Comment by znat** [comment]
@amitbend what's your OS?

**Comment by amitbend** [comment]
Ubuntu 18.04

**Comment by MatthieuJnon** [comment]
This is a known bug with Linux, we're currently working on it, and will update this issue when it's done.
In the meantime, this comment proposes a quick solution (https://github.com/botfront/botfront/issues/32#issuecomment-492233695)

**Comment by amitbend** [comment]
Thanks! I'll look into it.
BTW - great project! can't wait to see it working
